"""
Step 2 of the reframed process (SPEC.md §0): for EACH bear definition
generated by ground_truth_v2.py, find the best classifier against a
RELAXED target (80% coverage, <5% FPR - was 85%/<5%), using the same
4-signal voting architecture/parameter ranges that performed best against
the original 20%-rule ground truth (sweep4.py's GUIDED_RANGES).

Data (SPY/VIX/credit/breadth) is fetched once and shared across all 7
definition sweeps - only the ground truth (and therefore the loss/target
evaluation) changes per definition.

Usage:
    python sweep_multi_def.py --n 8000
"""
import argparse
import json
import os
import time
from dataclasses import asdict

from data_feed import load_all
from sweep import run_sweep_with_ranges, print_top, all_targets_met, combined_loss
from sweep4 import GUIDED_RANGES

DEFS_DIR = os.path.join(os.path.dirname(__file__), 'ground_truth_defs')
RESULTS_DIR = os.path.join(os.path.dirname(__file__), 'results')

COVERAGE_TARGET = 0.80
FPR_TARGET = 0.05
DEFRET_TARGET = 0.05


def load_def(name: str) -> dict:
    with open(os.path.join(DEFS_DIR, f'{name}.json')) as f:
        return json.load(f)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--n', type=int, default=8000, help='combos per definition')
    parser.add_argument('--seed', type=int, default=21)
    args = parser.parse_args()

    def_names = sorted(f[:-5] for f in os.listdir(DEFS_DIR) if f.endswith('.json'))
    print(f'Found {len(def_names)} definitions: {def_names}')

    print('Loading shared data (SPY/VIX/credit/breadth) once...')
    data = load_all()

    os.makedirs(RESULTS_DIR, exist_ok=True)
    summary = {}

    for name in def_names:
        gt = load_def(name)
        print(f"\n{'='*90}\nDefinition: {name}  "
              f"(style={gt['style']}, threshold={gt['threshold']:.0%}, window={gt['window']}, "
              f"{gt['n_episodes']} episodes, {gt['total_decline_days']} decline-days)\n{'='*90}")

        t0 = time.time()
        results = run_sweep_with_ranges(
            args.n, args.seed, GUIDED_RANGES, data=data, gt=gt,
            coverage_target=COVERAGE_TARGET, fpr_target=FPR_TARGET, defret_target=DEFRET_TARGET,
            quiet=True,
        )
        elapsed = time.time() - t0
        print(f'  swept {args.n} combos in {elapsed:.1f}s')

        best_loss, best_params, best_result = results[0]
        passed = all_targets_met(best_result, COVERAGE_TARGET, FPR_TARGET, DEFRET_TARGET)
        print(f"  BEST: loss={best_loss:.4f}  cov={best_result['coverage']*100:.1f}%  "
              f"fpr={best_result['false_positive_rate']*100:.1f}%  "
              f"defret={best_result['defensive_cum_return']*100:.1f}%"
              f"{'  <<< TARGETS MET' if passed else ''}")

        n_passing = sum(1 for r in results if all_targets_met(r[2], COVERAGE_TARGET, FPR_TARGET, DEFRET_TARGET))
        print(f'  {n_passing}/{len(results)} combos met the 80%/<5%/>5% targets')

        summary[name] = {
            'n_episodes': gt['n_episodes'], 'total_decline_days': gt['total_decline_days'],
            'best_loss': best_loss, 'best_params': asdict(best_params),
            'coverage': best_result['coverage'], 'false_positive_rate': best_result['false_positive_rate'],
            'defensive_cum_return': best_result['defensive_cum_return'],
            'n_passing': n_passing, 'n_swept': len(results),
        }

        # Save top 10 per definition
        top10 = []
        for loss, params, res in results[:10]:
            top10.append({'loss': loss, 'params': asdict(params), 'coverage': res['coverage'],
                           'false_positive_rate': res['false_positive_rate'],
                           'defensive_cum_return': res['defensive_cum_return']})
        with open(os.path.join(RESULTS_DIR, f'multi_def_{name}_top10.json'), 'w') as f:
            json.dump(top10, f, indent=2)

    with open(os.path.join(RESULTS_DIR, 'multi_def_summary.json'), 'w') as f:
        json.dump(summary, f, indent=2)

    print(f"\n{'='*90}\nSUMMARY (best classifier per definition, target 80%/<5%/>5%)\n{'='*90}")
    print(f"{'Definition':<18}{'Episodes':>9}{'Days':>7}{'Coverage':>10}{'FPR':>8}{'DefRet':>9}{'Passed?':>9}")
    for name, s in summary.items():
        passed = 'YES' if s['n_passing'] > 0 else 'no'
        print(f"{name:<18}{s['n_episodes']:>9}{s['total_decline_days']:>7}"
              f"{s['coverage']*100:>9.1f}%{s['false_positive_rate']*100:>7.1f}%"
              f"{s['defensive_cum_return']*100:>8.1f}%{passed:>9}")

    print(f"\nSaved results/multi_def_summary.json and per-definition top10 files")


if __name__ == '__main__':
    main()
